service: fastapi-serverless-example

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin
custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: my-fastapi-serverless-app-layer
      description: My fastapi serverless app layer
      compatibleRuntimes:
        - python3.8
  prune:
    automatic: true
    includeLayers: true
    number: 10

functions:
  app:
    package:
      include:
        - "main.py"
        - "app"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
        - "venv/**"

    handler: app.main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}